### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by khaled-305** [lenard123/Voting-System#1]
very nice application... but after i finished installing everything, it shows a blank page on the browser instead of a welcome page or an index page

**Comment by ghost** [comment]
I also only see a white page like @khaled-305 
@lenard123 have you a demo version where I can see how it looks like online ?

**Comment by ayagaidi** [comment]
after i finished installing everything, it shows a blank page ,what is wrong ?

**Comment by lenard123** [comment]
@khaled-305 @kerim80 @ayagaidi 
Can i see some screenshots of your browser console

**Comment by lenard123** [comment]
> I also only see a white page like @khaled-305
> @lenard123 have you a demo version where I can see how it looks like online ?

Here's a link to the System demo https://youtu.be/dsEoONiovdA

**Comment by lenard123** [comment]
If you're not using the default URL provided by laravel (http://localhost:8000/)
update the config.js https://github.com/lenard123/Voting-System/blob/master/public/js/config.js
and set the right URL you are using.
