### ISSUE TITLE
can't log in

### ISSUE THREAD

**Issue by OluStephen-code** [lenard123/Voting-System#6]
Even after entering the email and password stated, it just keeps loading "logging in" for some secs and will not log me in. please how can I address that issue?

**Comment by lenard123** [comment]
@OluStephen-code The problem might be in the database,
can you please send some screenshots of your browser console?

**Comment by CAUN94** [comment]
i have the same problem

**Comment by prashantsingh2408** [comment]
I can't able to login with admin,it does not show any error message.

**Comment by lenard123** [comment]
> I can't able to login with admin,it does not show any error message.

Please send me some screenshots of your browser console.

**Comment by FahimAnzamDip** [comment]
![image](https://user-images.githubusercontent.com/37371749/104819791-06d73480-585a-11eb-84a8-b6ee9067e013.png)
Login Problem

**Comment by lenard123** [comment]
The error was caused by the config.js, the url is set only in https://localhost:8000/
So the system throws an error when used in a different URL.

I remove the config.js, and directly configure the system through the admin.blade.php, and index.blade.php
to fix the issue.
