### ISSUE TITLE
can't log in

### ISSUE THREAD

**Issue by CAUN94** [lenard123/Voting-System#7]
i enter a few time and works, perfectly but now i try no enter and i only receive a message that says "logging in"

**Comment by lenard123** [comment]
@CAUN94 
can you please send some screenshots of your browser console?

**Comment by CAUN94** [comment]
![Captura de Pantalla 2020-03-23 a la(s) 20 27 17](https://user-images.githubusercontent.com/11137109/77372595-b92a9200-6d44-11ea-9f77-950005af26f6.png)

**Comment by CAUN94** [comment]
did you find the problem?

**Comment by ktmsulaim** [comment]
> did you find the problem?

If you are using custom domain for eg (voting.dev) or else this problem will occure. Try to run `php artisan serve` and make sure it's served as http://localhost:8000. It works fine!

**Comment by lenard123** [comment]
> ![Captura de Pantalla 2020-03-23 a la(s) 20 27 17](https://user-images.githubusercontent.com/11137109/77372595-b92a9200-6d44-11ea-9f77-950005af26f6.png)

I added a config..js file in case you're not using the default URL provided by laravel.
https://github.com/lenard123/Voting-System/blob/master/public/js/config.js
